/////////////////////////////////////////////////////////////
///////////////////////ROUTES PRODUCTS///////////////////////
/////////////////////////////////////////////////////////////
GET http://localhost:8080/products
################################
GET http://localhost:8080/products/sort
################################
http://localhost:8080/products/tri?name=b
################################
GET http://localhost:8080/products/sortPrice
################################
GET http://localhost:8080/products/5e4d49d80a3d603d6e4fdcdd
################################
PATCH http://localhost:8080/products/5e4d49d80a3d603d6e4fdcfe
################################
DELETE http://localhost:8080/products/5e4d49d80a3d603d6e4fdcfe
################################
POST http://localhost:8080/products/add
################################

/////////////////////////////////////////////////////////////
//////////////////////ROUTES CATEGORIES//////////////////////
/////////////////////////////////////////////////////////////
GET http://localhost:8080/categories
################################
GET http://localhost:8080/categories/5e4e598db07d2c4c1da1e39a
################################
GET http://localhost:8080/
################################

/////////////////////////////////////////////////////////////
////////////////ROUTES SHOPPINGCARTS/////////////////////////
/////////////////////////////////////////////////////////////
GET http://localhost:8080/shoppingCart
################################
GET http://localhost:8080/shoppingCart/5e4fd53b72be020540614df8
################################
DELETE http://localhost:8080/shoppingCart/5e4fd53b72be020540614df8/product/5e4d49d80a3d603d6e4fdcdc

# db.getCollection("carts").deleteOne({}, { $pull: { products: { _id: "5e4d49d80a3d603d6e4fdcdc" } } }, {multi:true})
################################

/////////////////////////////////////////////////////////////
///////////////////////ROUTES USERS//////////////////////////
/////////////////////////////////////////////////////////////
GET http://localhost:8080/users
################################
GET http://localhost:8080/users/5e523a0aa934b42de0eb5c66
################################
POST http://localhost:8080/users
Content-Type: application/json

{
    "gender": "Monsieur",
    "lastname": "François",
    "firstname": "MARION",
    "dateOfBirth": "31/12/1987",
    "username": "francoisdevtest",
    "password": "francois13",
    "email": "johnwick@gmail.com",
    "phone": "",
    "cards": [
        { "cardNumber": "323242535837468364", "cardUserName": "MR MARION FRANCOIS", "cardDate": "13/01/2022", "cardSecretVerif": "743" },
        { "cardNumber": "323242535837469878", "cardUserName": "MR MARION FRANCOIS", "cardDate": "13/01/2021", "cardSecretVerif": "325" }
    ],
    "adresses": [
        { "adresse1": "23 rue des lilas", "adresse2": null, "codePostal": "21210", "ville": "SAULIEU" },
        { "adresse1": "55 avenue du général de gaulle", "adresse2": "chemin bis", "codePostal": "13100", "ville": "AIX EN PROVENCE" }
    ]
}
################################
POST http://localhost:8080/users/login
Content-Type: application/json

{
    "username": "francoisdevtest",
    "password": "francois13"
}
################################

GET http://localhost:8080/admins
################################

POST http://localhost:8080/admins/login
Content-Type: application/json

{
    "firstname" : "test",
    "lastname" : "test",
    "username": "test",
    "password": "test"
}
