/////////////////////////////////////////////////////////////
///////////////////////ROUTES PRODUCTS///////////////////////
/////////////////////////////////////////////////////////////
GET http://localhost:8080/products
################################
GET http://localhost:8080/products/5e4d49d80a3d603d6e4fdcdd
################################
PATCH http://localhost:8080/products/5e4d49d80a3d603d6e4fdcfe
################################
DELETE http://localhost:8080/products/5e4d49d80a3d603d6e4fdcfe
################################
POST http://localhost:8080/products/add
################################
/////////////////////////////////////////////////////////////
//////////////////////ROUTES CATEGORIES//////////////////////
/////////////////////////////////////////////////////////////
GET http://localhost:8080/categories
################################
GET http://localhost:8080/categories/5e4e598db07d2c4c1da1e39a
################################
GET http://localhost:8080/
################################
/////////////////////////////////////////////////////////////
////////////////ROUTES SHOPPINGCARTS/////////////////////////
/////////////////////////////////////////////////////////////
GET http://localhost:8080/shoppingCart
################################
GET http://localhost:8080/shoppingCart/5e4fd53b72be020540614df7
################################